<?php
/**
 * File: reports_registration.module
 * Version: 7103
 * Created: 8/9/2015
 *
 */
/**
 * @file
 * Affords administrators the ability to associate OSU courses and students with the Write 365 application
 * Creates the instructor role provides instructors with student reports (word counts, etc.)
 *
 */
function course_detail()
{
    return 'This feature not yet implemented (build 20150927).';
}

/**
 * @return string Course listing for the instructor reports
 */
function course_list()
{
    global $user;

    $header = array(
        array(
            'data' => t('Report by CRN'),
            'field' => 'i.crn',
            'sort' => 'desc'
        ),
        array(
            'data' => t('Instructor'),
            'field' => 'i.instructor_name',
            'sort' => 'desc',
        ),
        array(
            'data' => t('Course Name'),
            'field' => 'i.course_name',
            'sort' => 'desc',
        ),
        array(
            'data' => t('Section Number'),
            'field' => 'i.section_number',
            'sort' => 'desc',
        ),
        array(
            'data' => t('Term'),
            'field' => 'i.term',
            'sort' => 'desc',
        ),
    );

    $courses = db_select('OSU_Registration_Instructor_Input', 'i');
    //$courses->join('OSU_Reports_Registration', 'r', 'i.term = r.currentterm');
    $courses->fields('i', array('crn', 'instructor_name', 'course_name', 'section_number', 'term'));
    $courses->addTag('node access');
    $courses->condition('i.onid', $user->name, '=');

    $table_sort = $courses->extend('TableSort')
        ->orderByHeader($header); //then use an extender to create the sorted table
    $pager = $table_sort->extend('PagerDefault')
        ->limit(20);    //take the sorted table and extend that with a pager
    $result = $pager->execute(); // execute the result
    $rows[] = array();
    foreach ($result as $row) { // add the data
        $crn = $row->crn;
        $courseName = $row->course_name;
        $sectionNumber = $row->section_number;
        $instructorName = $row->instructor_name;
        $term = $row->term;

        $form = "<form name=\"courses\" action=\"http://tac-dev.nws.oregonstate.edu/W365_reporting/course_report.php\" method=\"post\">" .
            "<input type=\"hidden\" name=\"crs_crn\" value=\"".$crn."\">" .
            "<input type=\"hidden\" name=\"crs_name\" value=\"".$courseName."\">" .
            "<input type=\"hidden\" name=\"crs_section\" value=\"".$sectionNumber."\">" .
            "<input type=\"hidden\" name=\"crs_instructor\" value=\"".$instructorName."\">" .
            "<input type=\"hidden\" name=\"crs_term\" value=\"$term\">" .
            "<input type=\"submit\" value=\"View ". $crn . "\">" .
            "</form>";
        $rows[$crn]['crn'] = $form;
        $rows[$crn]['instructor_name'] = $row->instructor_name;
        $rows[$crn]['course_name'] = $row->course_name;
        $rows[$crn]['section_number'] = $row->section_number;
        $rows[$crn]['term'] = $row->term;
    }
    // and then theme in the same order.
    // first, theme the table
    // and then theme the pager.
    $build = "<p>The following are your courses registered with the Write 365 application (across all terms).</p>
                <p>Note: Columns are sortable. Click on the column heading to change the sort order.</p>";
    $build .= theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('id' => 'sort-table')));
    $build .= theme('pager');

    return $build; // done

}

/**
 * Implements hook_block_info().
 */
function reports_registration_block_info()
{
    $blocks = array();
    $blocks['instructor_links'] = array(
        'info' => t('Instructor reports'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function reports_registration_block_view($delta = '')
{
    if ($delta == 'instructor_links') {
        $list = array(
            'current' => l('Section List', 'reports_registration/instructor/reports'),
        );
        $theme_args = array('items' => $list, 'type' => 'ul');
        $content = theme('item_list', $theme_args);
        $block = array(
            'subject' => t('Instructor Reports'),
            'content' => $content,
        );
        if (user_access('view instructor reports')) {
            return $block;
        }

    }
}

/**
 * Define the module's roles and weights
 */
function reports_registration_default_roles()
{
    $roles = array();
    $roles ['Instructor'] = array(
        'name' => 'instructor',
        'weight' => '3'
    );
    return $roles;
}

/**
 * Implements hook_help()
 */
function reports_registration_help($path, $arg)
{
    switch ($path) {
        case 'admin/help#reports_registration';
            $output = '<h3>' . t('About:') . '</h3>';
            $output .= '<p>' . t('The Write 365 Report and Registration module affords administrators with the ability to associate classes and students with the Write 365 application.');
            $output .= '<p>' . t('Administrators will upload CSV files downloaded from Banner/DataWarehouse/Core into the Write 365 database.');
            $output .= '<h3>' . t('Useage:') . '</h3>';
            $output .= '<p>' . t('Course association files (course files) should be uploaded "one record per row" in the following format and column order:');
            $output .= '<p><table><tr><th>id (database unique auto increment value).</th>
 					<th>Instructor\'s ONID User Name (NOT ONID email address)</th>
 					<th>Instructor\'s OSU ID Number</th>
 					<th>Instructor\'s name in LMF format (e.g., Bennett, Dennis R)</th>
 					<th>Course CRN</th>
 					<th>Course Name (e.g., WR 121)</th>
 					<th>Section Number (e.g., 402)</th>
 					</tr></table></p>';
            $output .= '<p>' . t('Student enrollment files (registration files) should be uploaded "one record per row" in the following format and column order:');
            $output .= '<p><table><tr><th>Student ID number</th>
 					<th>Student\'s ONID User name (NOT ONID email address)</th>
 					<th>Student\'s Last Name</th>
 					<th>Student\'s First Name</th>
 					<th>Student\'s Email Address</th>
 					<th>Current OSU Term Number(e.g., 201601)</th>
 					<th>Coure Name (e.g., WR 121)</th>
 					<th>Instructor Name in LFM format (e.g., Bennett, Dennis R)</th>
 					<th>Course CRN</th>
 					<th>Section Number (e.g., 402)</th>
 					</tr></table></p>';
            $output .= '<strong>' . t('Please note that course files and registration files will be uploaded separately.');
            return $output;

    }
}

/**
 * Implements hook_menu().
 */
function reports_registration_menu()
{
    $items = array();
    /**
    $items['admin/config/people/reports_registration'] = array(
        'title' => 'OSU Write 365 Reports and Registration',
        'description' => 'Reports, Registration, and Configuration Page for the Oregon State University Write 365 installation.',
        'page callback' => 'drupal_get_form',
        'access arguments' => array('administer reports and registrations'),
        'type' => MENU_NORMAL_ITEM,
    );
     **/
    $items['reports_registration/instructor/reports'] = array(
        'title' => 'Section Report',
        'description' => 'Your Write 365 section listing.',
        'page callback' => 'course_list',
        'access arguments' => array('view instructor reports'),
        'type' => MENU_NORMAL_ITEM,
    );
    /**
    $items['reports_registration/instructor/reports/detail'] = array(
        'title' => 'Detailed Student Report',
        'description' => 'Your detailed course report.',
        'page callback' => 'course_detail',
        'access arguments' => array('view instructor reports'),
        'type' => MENU_VISIBLE_IN_BREADCRUMB,
    );
     **/
    return $items;
}

/**
 * Implements hook_permission
 */
function reports_registration_permission()
{
    return array(
        'administer reports and registrations' => array(
            'title' => t('Administer Reports and Registrations'),
            'description' => t('Administer Module, view all instructor reports, upload student and instructor data'),
        ),
        'view instructor reports' => array(
            'title' => t('View Instructor Reports'),
            'description' => t('View Instructor Reports (cannot view student writing)'),
        ),
    );
}

/**
 * Implements hook_user_login().
 */
function reports_registration_user_login(&$edit, $account)
{

    global $user;
    if (in_array('instructor', $user->roles)) {
        drupal_set_message("Welcome back to Write 365.");
        return;
    } else {
        $instructorID = db_select('OSU_Registration_Instructor_Input', 'i')
            ->fields('i', array('onid'))
            ->condition('onid', $user->name, '=')
            ->execute()
            ->fetchAssoc();
    }
    if ($instructorID != '') {
        drupal_set_message('You are being registered as a Write 365 instructor.');
        $result = db_select('role', 'r')
            ->fields('r')
            ->condition('name', 'instructor', '=')
            ->execute()
            ->fetchAssoc();
        $rid = $result['rid'];
        $instructorRoles = array(
            'uid' => $user->uid,
            'rid' => $rid,
        );
        db_insert('users_roles')
            ->fields($instructorRoles)
            ->execute();
        drupal_set_message('Instructor role set.');
    } else {
        drupal_set_message('Welcome to Write 365.');
    }
    return;
}
